finder/urls.py
from django.urls import path, include
from django.views.generic import TemplateView


from . import views

app_name = 'finder'
urlpatterns = [
    path('', views.top_stories_index, name='top_stories_index'),
    path('profile/', TemplateView.as_view(template_name='finder/profile.html'), name='profile'),
    path('login/', TemplateView.as_view(template_name='finder/login.html'), name='login'),
    path('logout/', TemplateView.as_view(template_name='finder/logout.html'), name='logout'),
    path('profile/edit', views.profile, name='edit_profile'),
    path('search/', views.search, name='search'),
    path('top_stories/', views.top_stories_home, name='top_stories_home'),
    path('friendlist/', views.friendlist_home, name='friendlist_home'),
    path('sendRequest/<int:id>/', views.send_FriendRequest, name='send_request'),
    path('cancelRequest/<int:id>/', views.cancel_FriendRequest, name='cancel_request'),
    path('deleteRequest/<int:id>/', views.delete_FriendRequest, name='delete_request'),
    path('acceptRequest/<int:id>/', views.accept_FriendRequest, name='accept_request'),
    path('removeFriend/<int:id>/', views.remove_Friend, name='remove_friend'),
    path('groups/', views.groups, name='groups'),
    path('cancel_group_invite/<int:id>/', views.cancel_group_invite, name='cancel_group_invite'),
    path('invite_to_group/<int:id>/', views.invite_to_group, name='invite_to_group'),
    path('accept_group_request/<int:id>/', views.accept_GroupRequest, name='accept_group_request'),
    path('delete_group_request/<int:id>/', views.delete_GroupRequest, name='delete_group_request'),
    path('leave_group/', views.leave_group, name='leave_group'),
    path('create_group/', views.create_group, name='create_group'),
    path('<str:group_name>/', views.view_group, name="view_group")
]

virtualstudyfinder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='finder/landing.html')),
    path('finder/', include('finder.urls')),
    path('accounts/', include('allauth.urls'), name='account'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finder/models.py
'''***************************************************************************************
*  Title: Python Django Tutorial: Full-Featured Web App Part 9 - Update User Profile
*  Author: Corey Schafer
*  Date: 2/18/19
*  URL_1: https://www.youtube.com/watch?v=CQ90L5jfldw&t
*  URL_2: https://github.com/CoreyMSchafer/code_snippets/tree/master/Django_Blog
*  Software License: MIT

*  Title: Python Django Tutorial: Full-Featured Web App Part 8 - User Profile and Picture
*  Author: Corey Schafer
*  Date: 2/18/19
*  URL_1: https://www.youtube.com/watch?v=FdVuKt_iuSI&t
*  URL_2: https://github.com/CoreyMSchafer/code_snippets/tree/master/Django_Blog
*  Software License: MIT
***************************************************************************************'''

from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.contrib.auth.models import AbstractUser
from phone_field import PhoneField
from .data import LIST_MAJORS, GRADUATION_YEARS, LIST_GENDERS



# Create your models here.
class Account(models.Model):
    username = models.CharField(max_length=100, primary_key=True)
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.username
        
class ProfileManager(models.Manager):
    def create_profile(self, user, name='', image='', phone='', major='', minor='', graduation='', gender='', age='', zoom_link=''):
        user_created = self.create(user=user, name=name, image=image, phone=phone, major=major, minor=minor, graduation=graduation, gender=gender, age=age, zoom_link=zoom_link)
        return user_created


class Group(models.Model):
    group_name = models.CharField(max_length=255, default='',null=True)
    group_zoom_link = models.CharField(max_length=255, default='',null=True)
    members = models.ForeignKey("Profile", related_name="members", on_delete=models.CASCADE,blank=True, null=True)

    def __str__(self):
        return f'{self.group_name}'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, null=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    phone = PhoneField(default='', blank=True, null=True)
    major = models.CharField(max_length=255, choices=LIST_MAJORS, default='', null=True)
    minor = models.CharField(max_length=255, choices=LIST_MAJORS, default='', null=True, blank=True)
    graduation = models.CharField(max_length=255, choices=GRADUATION_YEARS, default='',null=True )
    gender = models.CharField(max_length=255, choices=LIST_GENDERS, default='', null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    friends = models.ManyToManyField("Profile", blank=True)

    group = models.CharField(max_length=255, default='', null=True)
    group_leader = False
    group_valid = True
    group_zoom_link = models.URLField(max_length=255, default='', null=True)
    group_members = models.ForeignKey(User, related_name="group_members", on_delete=models.CASCADE, blank=True, null=True)
    # group = models.ForeignKey("Group", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} Profile'

class FriendRequest(models.Model):
    to_user = models.ForeignKey(User, related_name='to_user', on_delete=models.CASCADE)
    from_user = models.ForeignKey(User, related_name='from_user', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'From {self.from_user.username}, to {self.to_user.username}'

class GroupRequest(models.Model):
    to_user = models.ForeignKey(User, related_name='group_to_user', on_delete=models.CASCADE)
    from_user = models.ForeignKey(User, related_name='group_from_user', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Group request from {self.from_user.username}, to {self.to_user.username}'

finder/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Account, Profile

class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username']

class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['image', 'name', 'gender', 'age', 'phone', 'major', 'minor', 'graduation']

finder/views.py
'''***************************************************************************************
*  REFERENCES
*  Title: django-filter 2.4.0
*  Author: Alex Gaynor
*  Date: Not Provided
*  Code version: 2.4.0
*  URL: https://pypi.org/project/django-filter/
*  Software License: BSD

*  Title: newsapi-python
*  Author: Matt Lisivick
*  Date: 10/3/19
*  Code version: 2.0
*  URL: https://github.com/mattlisiv/newsapi-python
*  Software License: MIT

*  Title: Python Django Tutorial: Full-Featured Web App Part 9 - Update User Profile
*  Author: Corey Schafer
*  Date: 2/18/19
*  URL_1: https://www.youtube.com/watch?v=CQ90L5jfldw&t
*  URL_2: https://github.com/CoreyMSchafer/code_snippets/tree/master/Django_Blog
*  Software License: MIT

*  Title: Python Django Tutorial: Full-Featured Web App Part 8 - User Profile and Picture
*  Author: Corey Schafer
*  Date: 2/18/19
*  URL_1: https://www.youtube.com/watch?v=FdVuKt_iuSI&t
*  URL_2: https://github.com/CoreyMSchafer/code_snippets/tree/master/Django_Blog
*  Software License: MIT

* Title: Django-allauth Tutorial
* Author: Will Vincent
* Date: 11/10/20
* URL: https://learndjango.com/tutorials/django-allauth-tutorial
* Software License: MIT

*  Title: Django Friends tutorial // How to create a Facebook-like system.
*  Author: JustDjango
*  Date: 4/22/18
*  URL_1: https://www.youtube.com/watch?v=QS9z4g0JAOY
*  URL_2: https://github.com/justdjango/friends
*  Software License: BSD
***************************************************************************************'''


from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Account, Profile, FriendRequest, GroupRequest
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.template import loader
from django.contrib.auth.decorators import login_required
from finder.forms import UserRegisterForm, ProfileUpdateForm, UserUpdateForm
from django.views.generic import FormView, UpdateView
from django.urls import reverse
from .filters import DropdownFilter
from django.contrib.auth.models import Group, Permission
from django.db.models import Q
import requests

# Create your views here.

def index(request):
    #if request.method == 'POST':
    #    form = UserCreationForm(request.POST)
    #    if form.is_valid():
    #        form.save()
    #        username = Account.objects.order_by('username')
    #else:
    #    form = UserCreationForm()
    #return render(request, 'finder/index.html', {'form':form})
    users = Account.objects.order_by('username')
    template = loader.get_template('finder/index.html')
    context = {'users': users}
    return HttpResponse(template.render(context, request))



@login_required
def search(request):
    #current_user = Profile.objects.all()
    users = Profile.objects.all()
    friendreq = FriendRequest.objects.all()
    freqsto=[]
    for friendob in friendreq:
        if request.user == friendob.from_user:
            freqsto.append((friendob.to_user).id)
    groupreq = GroupRequest.objects.all()
    greqsto=[]
    for groupob in groupreq:
        if request.user == groupob.from_user:
            greqsto.append((groupob.to_user.id))
    valid = Profile.objects.get(user=request.user).group != ""
    #checks = request.POST.getlist('checks')
    profile_filter = DropdownFilter(request.GET, queryset=users)
    template = loader.get_template('finder/search.html')
    '''major = False
    yog = False
    specific_major = ""
    specific_yog = ""
    for check in checks:
        if(check == "1"):
            major = True
            specific_major = request.Post.get('specific_major')
        elif(check == "2"):
            yog = True
            specific_yog = request.POST.get("specific_yog")
    new_users = []
    if(major == True and yog == True):
        for user in users:
            if(user.major == specific_major and user.graduation == specific_yog):
                new_users.append(user)
        context = {'users': new_users}
        return HttpResponse(template.render(context, request))
    elif(major == True):
        for user in users:
            if(user.major == specific_major):
                new_users.append(user)
        context = {'users': new_users}
        return HttpResponse(template.render(context, request))
    elif(yog == True):
        for user in users:
            if(user.graduation == specific_yog):
                new_users.append(user)
        context = {'users': new_users}
        return HttpResponse(template.render(context, request))
    '''
    #context = {'users': users}
    return HttpResponse(template.render({'filter': profile_filter,'freqsto': freqsto, 'greqsto':greqsto, 'valid':valid}, request))


def login(request):
    return HttpResponse("You are at the login screen")

def user_detail(request, username):
    return HttpResponse("You're looking at the account with username:  %s." % username)

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('../profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'finder/edit_profile.html', context)

@login_required
def send_FriendRequest(request,id):
    from_user=request.user
    to_user=(Profile.objects.get(id=id)).user
    frequest=FriendRequest.objects.get_or_create(from_user=from_user,to_user=to_user)
    return redirect('/finder/search')

@login_required
def cancel_FriendRequest(request,id):
    from_user=request.user
    to_user=(Profile.objects.get(id=id)).user
    frequest=FriendRequest.objects.get(from_user=from_user,to_user=to_user)
    frequest.delete()
    return redirect('/finder/search')

@login_required
def accept_FriendRequest(request,id):
    user1=request.user
    profile1=Profile.objects.get(user=user1)
    profile2=Profile.objects.get(id=id)
    user2=profile2.user
    frequest=FriendRequest.objects.get(from_user=user2,to_user=user1)
    profile1.friends.add(profile2)
    profile2.friends.add(profile1)
    frequest.delete()
    return redirect('/finder/friendlist')

@login_required
def delete_FriendRequest(request,id):
    user1=request.user
    profile1=Profile.objects.get(user=user1)
    profile2=Profile.objects.get(id=id)
    user2=profile2.user
    frequest=FriendRequest.objects.get(from_user=user2,to_user=user1)
    frequest.delete()
    return redirect('/finder/friendlist')

@login_required
def remove_Friend(request,id):
    user1=request.user
    profile1=Profile.objects.get(user=user1)
    profile2=Profile.objects.get(id=id)
    user2=profile2.user
    profile1.friends.remove(profile2)
    profile2.friends.remove(profile1)
    return redirect('/finder/friendlist')

@login_required
def friendlist_home(request):
    friends = Profile.objects.get(user=request.user).friends.all()
    friendreq = FriendRequest.objects.all()
    freqs= []
    pendingReq = False
    for friendob in friendreq:
        if request.user == friendob.to_user:
            freqs.append(friendob.from_user)
            pendingReq = True
    for i in range(len(freqs)):
        freqs[i]=Profile.objects.get(id=(freqs[i]).id)
    template = loader.get_template('finder/FriendList.html')
    context = {'friends': friends, 'freqs': freqs, 'pendingReq': pendingReq}
    return HttpResponse(template.render(context, request))

@login_required
def create_group(request):
    group_name = request.POST.get('group_name')
    group_zoom_link = request.POST.get('group_zoom_link')
    profile1 = Profile.objects.get(user=request.user)

    if len(list(Profile.objects.filter(group=group_name))) == 0:
        profile1.group = group_name
        profile1.group_zoom_link = group_zoom_link
        profile1.group_leader = True
        profile1.group_valid = True
        profile1.save()

        groupreq = GroupRequest.objects.all()
        for groupob in groupreq:
            if request.user == groupob.from_user:
                groupob.delete()
    else:
        if group_name != "":
            profile1.group_valid = False
            profile1.save()
    group_invite = ''
    group = Profile.objects.get(user=request.user).group
    groupreq = GroupRequest.objects.all()
    greqs = []
    pendingReq = False
    for groupob in groupreq:
        if request.user == groupob.to_user:
            greqs.append(groupob.from_user)
            group_invite = Profile.objects.get(user=groupob.from_user).group
            pendingReq = True
    for i in range(len(greqs)):
        greqs[i] = Profile.objects.get(id=(greqs[i]).id)
    template = loader.get_template('finder/groups.html')
    context = {'group_invite': group_invite, 'greqs': greqs, 'pendingReq': pendingReq, 'group': group,'valid': profile1.group_valid}
    return HttpResponse(template.render(context, request))


@login_required
def invite_to_group(request, id):
    from_user=request.user
    to_user=(Profile.objects.get(id=id)).user
    GroupRequest.objects.get_or_create(from_user=from_user, to_user=to_user)
    return redirect('/finder/search')

@login_required
def cancel_group_invite(request,id):
    from_user=request.user
    to_user=(Profile.objects.get(id=id)).user
    grequest=GroupRequest.objects.get(from_user=from_user,to_user=to_user)
    grequest.delete()
    return redirect('/finder/search')

@login_required
def groups(request):
    group_invite = ''
    group = Profile.objects.get(user=request.user).group
    groupreq = GroupRequest.objects.all()
    greqs= []

finder/templates/finder/FriendList.html
{% extends "finder/base.html" %}
{% load crispy_forms_tags %}
{% load socialaccount %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
  <head>
      <title>Friends List</title>
    </head>
    <body>
    {% if pendingReq %}
    <h2 class="text-primary">Pending requests</h2>
      {% for friend in freqs %}
      <div class="content-section">
        <div class="media">
          <div style="width:20%; float:left">
            {% if friend.image.url %}
            <img class="rounded-circle account-img" src="{{friend.image.url}}">
            {% else %}
            <img class="rounded-circle account-img" src="{% static 'finder/default.jpg' %}">
            {% endif %}
          </div>
          <div style="width:80%; float:right">
              <p style="font-weight: bold; color:#232D4B; font-size:30px;" >{{friend.name}}</p>
              <p class="text-secondary">Email: {{friend.user.email}}</p>
              <p class="text-secondary">Phone: {{friend.phone}}</p>
              <p class="text-secondary">Major: {{friend.major}}</p>
              <p class="text-secondary">Graduation: {{friend.graduation}}</p>
              <a href="../acceptRequest/{{friend.id}}/"><button style="color:black;" class="btn btn-outline-info">Accept Friend</button></a>
              <a href="../deleteRequest/{{friend.id}}/"><button style="color:#FF0000;" class="btn btn-outline-info">Delete Request</button></a>
          </div>
        </div>
      </div>
      {% endfor %}
    {% endif %}
    <h1 style="color:#232D4B; padding-bottom: 20px">Friends</h1>
    {% for friend in friends %}
    <div class="content-section">
      <div class="media">
        <div style="width:20%; float:left">
            {% if friend.image.url %}
            <img class="rounded-circle account-img" src="{{friend.image.url}}">
            {% else %}
            <img class="rounded-circle account-img" src="{% static 'finder/default.jpg' %}">
            {% endif %}
        </div>
        <div style="width:80%; float:right">
            <p style="font-weight: bold; color:#232D4B; font-size:30px;" >{{friend.name}}</p>
            <p class="text-secondary">Email: {{friend.user.email}}</p>
            <p class="text-secondary">Phone: {{friend.phone}}</p>
            <p class="text-secondary">Major: {{friend.major}}</p>
            <p class="text-secondary">Graduation: {{friend.graduation}}</p>
            <a href="../removeFriend/{{friend.id}}/"><button style="color:#FF0000;" class="btn btn-outline-info">Remove Friend</button></a>
        </div>
      </div>
    </div>
    
    {% endfor %}
    
    </body>
    {% else %}
    <h1>Login Screen</h1>
    <p>Please login to see friend list</p>
    <a href="{% provider_login_url 'google' %}"><img src="{% static 'finder/signgoogle.png' %}"> </a>
  {% endif %}
  </html>
{% endblock content %}

finder/templates/finder/base.html
{% load static %}
{% load socialaccount %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>VSBFinder</title>
<!--
Classic Template
http://www.templatemo.com/tm-488-classic
-->
    <!-- load stylesheets -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">  <!-- Google web font "Open Sans" -->
    <link rel="stylesheet" type="text/css" href="{% static 'finder/templatemo-style.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'finder/bootstrap.min.css'%}">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
          <![endif]-->
</head>

    <body>
        <div class="tm-header">
            <div class="container-fluid">
                <div class="tm-header-inner">
                    <a href="../../finder"><img src="{% static 'finder/VSBF.png' %}" width="100" height="100"></a>
                    <!-- navbar -->
                    <nav class="navbar tm-main-nav">

                        <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#tmNavbar">
                            &#9776;
                        </button>
                        
                        {% if user.is_authenticated %}
                        <div class="collapse navbar-toggleable-sm" id="tmNavbar">
                            <ul class="nav navbar-nav">
                                <li class="nav-item">
                                    <a href="../../finder" class="nav-link">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a href="/finder/profile" class="nav-link">Profile</a>
                                </li>
                                <li class="nav-item">
                                    <a href="/finder/search" class="nav-link">Find Buddies</a>
                                </li>
                                <li class="nav-item">
                                    <a href="/finder/friendlist" class="nav-link">Friend's List</a>
                                </li>
                                <li class="nav-item">
                                    <a href="/finder/groups" class="nav-link">My Clan</a>
                                </li>
                                <li class="nav-item">
                                    <a href="/finder/top_stories" class="nav-link">Top Stories</a>
                                </li>
                                <li class="nav-item">
                                    <a style="color:red" href="/finder/logout" class="nav-link">Logout</a>
                                </li>
                            </ul>                        
                        </div>
                        {% else %}
                        <div class="collapse navbar-toggleable-sm" id="tmNavbar">
                            <ul class="nav navbar-nav">
                                <li class="nav-item">
                                    <a href="../../finder" class="nav-link">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a href="/finder/profile" class="nav-link">Profile</a>
                                </li>
                                <li class="nav-item">
                                    <a href="/finder/search" class="nav-link">Find Buddies</a>
                                </li>
                                <li class="nav-item">
                                    <a href="/finder/friendlist" class="nav-link">Friend's List</a>
                                </li>
                                <li class="nav-item">
                                    <a href="/finder/groups" class="nav-link">My Clan</a>
                                </li>
                                <li class="nav-item">
                                    <a href="/finder/top_stories" class="nav-link">Top Stories</a>
                                </li>
                                <li class="nav-item">
                                    <a style="color:blue" href="{% provider_login_url 'google' %}" class="nav-link">Login</a>
                                </li>
                            </ul>                        
                        </div>
                        {% endif %}
                        
                    </nav>  

                </div>                                  
            </div>            
        </div>

        <div class="tm-section">
            {% block content %}{% endblock %}
        </div>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
        <footer class="tm-footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-12 tm-copyright-col">
                        <p class="tm-copyright-text">&copy; 2020 The Grass Roots. All Rights Reserved.</p>
                    </div>
                </div>
            </div>
        </footer>

        <!-- load JS files -->
        <script src="js/jquery-1.11.3.min.js"></script>             <!-- jQuery (https://jquery.com/download/) -->
        <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script> <!-- Tether for Bootstrap, http://stackoverflow.com/questions/34567939/how-to-fix-the-error-error-bootstrap-tooltips-require-tether-http-github-h --> 
        <script src="js/bootstrap.min.js"></script>                 <!-- Bootstrap (http://v4-alpha.getbootstrap.com/) -->
       
</body>
</html>

finder/templates/finder/groups.html
{% extends "finder/base.html" %}
{% block content %}
{% load socialaccount %}
{% load static %}
  <html>
{% if user.is_authenticated %}
    <head>
      <title>Groups</title>
    </head>
    <body>
    <form   method="POST" role="form" action='{% url "finder:create_group" %}'>
   {% csrf_token %}
    <h1>Create Clan</h1>
    <div class="content-section">
    <h7 style="color:#E57200;">***One clan per user, if in existing clan, it will delete current clan.</h7>

     {% if valid %}
        <h5>Clan Name: <input type='text' name='group_name' value="{{ group_name }}" /></h5>
        {% else %}
        <h5>Clan Name: <input type='text' placeholder="Clan already exists" name='group_name' value="{{ group_name }}" /></h5>
        {% endif %}


    <h7 style="color:#E57200;">***Please generate a zoom room and enter the url for the group here. (i.e https://www.zoom.us/...)</h7>
    <h5>Group Zoom Link: <input type='url' name='group_zoom_link' value="{{ group_zoom_link }}" /></h5>
    <button class="btn btn-outline-info" type="submit" value="Create">Create</button>
    </div>
    </form>
    {% if pendingReq %}
    <h1 style="padding-bottom: 20px; padding-top: 20px">Pending Requests</h1>
      {% for greq in greqs %}
      <div class="content-section">
          <div class="media">
            <div style="width:20%; float:left">
              {% if greq.image.url %}
              <img class="rounded-circle account-img" src="{{greq.image.url}}">
              {% else %}
              <img class="rounded-circle account-img" src="{% static 'finder/default.jpg' %}">
              {% endif %}
            </div>
            <div style="width:80%; float:right">
              <div class="media-body">
                <p style="font-weight: bold; color:#232D4B; font-size:30px;" class="text-primary">{{greq.name}}</p>
                <p class="text-secondary">{{greq.phone}}</p>
                <p class="text-secondary">{{greq.major}}</p>
                <a href="../accept_group_request/{{greq.id}}/"><button style="color:black;" class="btn btn-outline-info">Accept Clan Invite</button></a>
                <a href="../delete_group_request/{{greq.id}}/"><button style="color:#FF0000;" class="btn btn-outline-info">Delete Clan Invite</button></a>
              </div>
            </div>
          </div>
      </div>
      {% endfor %}
    {% endif %}
        <h1 style="padding-bottom: 20px; padding-top: 20px">Your Clan</h1>
    {% if group %}
        <div class="content-section">
            <div class="media">
              <div class="media-body">
                <a href="../{{group}}" style="font-weight: bold; color:#232D4B; font-size:30px;">{{group}}</a>
                <br>
                <a href="../leave_group"><button style="color:#FF0000;" class="btn btn-outline-info">Leave Clan</button></a>
              </div>
            </div>
        </div>
    {% endif %}
    </body>
  {% else %}
    <h1>Login Screen</h1>
    <p>Please login to see groups</p>
    <a href="{% provider_login_url 'google' %}"><img src="{% static 'finder/signgoogle.png' %}"> </a>
  {% endif %}
  </html>
{% endblock content %}

finder/templates/finder/login.html
{% extends "finder/base.html" %}
{% block content %}
{% load static %}
<div class="tm-home-img-container">
    <img src="{% static 'finder/homepg.png' %}" class="img-fluid">
</div>
<br>  
  {% load socialaccount %}
  <html>
    <body>
    {% if user.is_authenticated %}
      {% if user.profile.major == "" %}
      <div>
        <h1>To get started, update your profile.</h1>
        <a href="/finder/profile/edit"><button style="color:black;" class="btn btn-outline-info">Edit Profile</button></a>
        <br>
      </div>
      {% else %}
      <br>
      <h1>Already Logged in</h1><br>  
      <h5>Welcome, {{ user.profile.name }}!</h5>
      {% endif %}
    {% else %}
      <div style="text-align:center;">
      <h1>Please Login.</h1>
      <h5>Please Login to use VSBFinder.</h5><br>
      </div>
      <p><br></p><br>
      <p><br></p><br>
      <p><br></p><br>
    {% endif %}

    </body>
  </html>
{% endblock content %}